# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path

block_cipher = None

a = Analysis(
    ['src/cli.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('config.toml', '.'),
    ],
    hiddenimports=[
        'src',
        'cryptography',
        'keyring',
        'qrcode',
        'playwright',
        'psutil',
        'portalocker',
        'prometheus_client',
        'fastapi',
        'uvicorn',
        'python-multipart',
        'multipart',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'jinja2',
        'pydantic',
        'httpx',
        'aiohttp',
        'apscheduler',
        'colorlog',
        'lxml',
        'bs4',
        'tomli',
        'tomli_w',
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL._imaging',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.PngImagePlugin',
        'PIL.ImageWin',
        'keyring.backends.Windows',
        'cryptography.fernet',
        'cryptography.hazmat.primitives.ciphers.aes',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.backends.openssl',
        'cryptography.hazmat.backends.openssl.aes',
        'cryptography.hazmat.backends.openssl.rsa',
        'cryptography.hazmat.backends.openssl.dsa',
        'cryptography.hazmat.backends.openssl.dh',
        'cryptography.hazmat.backends.openssl.ec',
        'cryptography.hazmat.backends.openssl.hmac',
        'cryptography.hazmat.backends.openssl.cmac',
        'cryptography.hazmat.backends.openssl.poly1305',
        'cryptography.hazmat.backends.openssl.chacha20poly1305',
        'cryptography.hazmat.backends.openssl.x25519',
        'cryptography.hazmat.backends.openssl.x448',
        'cryptography.hazmat.backends.openssl.ed25519',
        'cryptography.hazmat.backends.openssl.ed448',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='hoyo-code-monitor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico' if Path('assets/icon.ico').exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='hoyo-code-monitor',
)